# .latexmkrc generated by CMake from UseLatexMk.cmake starts here

@default_files = ('main.tex');
$bibtex = "@BIBTEX_COMPILER@ %O %S";
$dvips = "@DVIPS_CONVERTER@ %O -o %D %S";
$latex = "@LATEX_COMPILER@ -interaction=nonstopmode -shell-escape %O %S";
$make = "@CMAKE_MAKE_COMMAND@";
$makeindex = "@MAKEINDEX_COMPILER@ %O -o %D %S";
$out_dir = "@CMAKE_CURRENT_BINARY_DIR@";
$pdf_mode = 1;
$pdflatex = "@PDFLATEX_COMPILER@ -interaction=nonstopmode -shell-escape %O %S";
$ps2pdf = "@PS2PDF_CONVERTER@ %O %S %D";
$clean_ext = "aux bbl blg bst idx ind lof lot out loc toc acn acr alg glg glo"
           + " gls ist fls log fdb_latexmk lol loa";

# .latexmkrc generated by CMake from UseLatexMk.cmake ends here
